version: "3.3"
services:
  ftp:
    network_mode: bridge
    restart: always
    image: "bogem/ftp:latest"
    ports:
      - '20:20'
      - '21:21'
      - '47400-47470:47400-47470'
    environment:
      - FTP_USER=test_user
      - FTP_PASS=test_user_password
      - PASV_ADDRESS=127.0.0.1
    volumes:
      - ./storage:/home/vsftpd
